spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      properties:
        hibernate:
          default_batch_fetch_size: 100
          dialect: org.hibernate.dialect.MySQLDialect
          highlight_sql: true
          format_sql: true
          show_sql: true
          use_sql_comments: true
        open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
